BaSP-TG-07:  Update and delete admins
BaSP-a2022/alfon-b-trackgenix-server pull request #14
Opened 2022-10-18 01:10 UTC by maxidelfinoRR

2022-10-18 03:25 UTC, agustin-schiaffino commented
please remember to change the Asignees to yourself, and add as Reviewers to me and Alfon

2022-10-18 03:33 UTC, agustin-schiaffino commented
You are missing to add the postman collection with your methods, please add it

2022-10-18 12:31 UTC, agustin-schiaffino commented on src/data/admins.json
> +}
this shouldn't be on the admin.json file of the folder data, check the repo and look for the postman_collection.json file; you need to replace that file with this methods and delete the admin.json file from the data folder. Please let me know if you have any doubts about this.

2022-10-18 12:33 UTC, agustin-schiaffino commented on src/controllers/admins.js
> +        message: 'Deleted successfully',
please check the excel file to follow the convention to follow on the messages, so that everyone on the team has the same type of messages

2022-10-18 12:35 UTC, agustin-schiaffino commented on src/controllers/admins.js
> +      message: 'An error ocurred',
same as line 18

2022-10-18 12:35 UTC, agustin-schiaffino commented on src/controllers/admins.js
> +      message: 'An error ocurred',
same as line 18

2022-10-18 16:42 UTC, visojulian commented on src/validations/admins.js
> +    name: Joi.string().min(3).max(50),
remember add required() to every field

2022-10-18 17:49 UTC, agustin-schiaffino commented on src/validations/admins.js
> +    name: Joi.string().min(3).max(50),
good observation, I agree

2022-10-18 18:26 UTC, agustin-schiaffino commented on src/controllers/admins.js
> +    const admins = await Admins.findByIdAndDelete(id);
maybe we could name this deletedAdmin

2022-10-18 18:27 UTC, agustin-schiaffino commented on src/controllers/admins.js
> +    const admins = await Admins.findByIdAndUpdate(
maybe we could name this updatedAdmin

2022-10-19 00:26 UTC, agustin-schiaffino commented on src/controllers/admins.js
> +    const deleteAdmin = await Admins.findByIdAndDelete(id);
this should be deletedAdmin, please change it

2022-10-19 00:26 UTC, agustin-schiaffino commented on src/controllers/admins.js
> +    const updateAdmin = await Admins.findByIdAndUpdate(
this should be updatedAdmin, please change it

2022-10-19 00:45 UTC, agustin-schiaffino commented on src/controllers/admins.js
> +      message: 'id invalid',
please check this message to follow the convention on the excel file

2022-10-19 02:09 UTC, JuliMonte5 requested changes
I don't see any errors besides the postman collection comment, that will mix the endpoints and folders structure given by the problematic

2022-10-19 02:09 UTC, JuliMonte5 commented on postman_collection.json
> +        {
I'd create a folder to contain the endpoints, so the directory is postman_collection > Admins > {list of methods]

2022-10-20 00:44 UTC, agustin-schiaffino submitted a review, later dismissed

2022-10-20 20:16 UTC, agustin-schiaffino commented on src/controllers/admins.js
>  };
to keep the consistency with the rest of the resources, please change it and put like this:
```
export default {
  getAllAdmins,
  getAdminById,
  createAdmin,
  updateAdmins,
  deleteAdmins,
};
```

2022-10-20 20:19 UTC, agustin-schiaffino commented on src/routes/admins.js
> +  .put('/:id', adminValidation.validateUpdate, adminsControllers.updateAdmins)
here you should change validateUpdate to validateAdmin, because validateUpdate no longer exists

2022-10-20 20:30 UTC, agustin-schiaffino approved these changes

2022-10-20 20:30 UTC, merged